### ISSUE TITLE
matching PIDS and PORTS for killing process by port ?

### ISSUE THREAD

**Issue by gedw99** [dokku/procfile-util#126]
### Description of feature

Hey @josegonzalez 

what you think about the idea of killing a process by port.

Its a typical use case of your running various things that use ports and you get a port clash or you have some process running in another terminal.

You start up your Profile and it complains that port 5008 is used.

quasi example for kill. Need to also have a KillByPort also

```go

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/josegonzalez/cli-skeleton/command"
	"github.com/mitchellh/cli"

	"github.com/shirou/gopsutil/v3/process"
	// "process-util/commands"
	"process-util/commands"
)

func KillProcess(name string) error {
	processes, err := process.Processes()
	if err != nil {
		return err
	}
	for _, p := range processes {
		n, err := p.Name()
		if err != nil {
			return err
		}
		if n == name {
			return p.Kill()
		}
	}
	return fmt.Errorf("process not found")
}
```

**Comment by josegonzalez** [comment]
I don't think this is a great idea. For instance, if that port is 5000, on a Mac, thats related to Airplay, so we'd be killing something that is part of the OS.

This tool also doesn't even start processes - just interacts with a Procfile - so killing them seems out of scope.

**Comment by gedw99** [comment]
sure we dont want to kill system stuff using ports.

I mean our users stuff using ports.

**Comment by josegonzalez** [comment]
This tool doesn't start any processes though, it merely allows interacting with a Procfile. There are other tools out there that do process management via the Procfile - `honcho` and `foreman` are two of them - where this sort of tool might be a better fit though, and I recommend following up in the one closest to your language (there are several out there written in various languages that start/stop processes).

**Comment by gedw99** [comment]
I know it does not start any processes. For example there is foreman that’s written in golang and works on any OS.

What I am aiming for it to be able to edit the Procfile via your tool.

**Comment by josegonzalez** [comment]
I think we're speaking past each other here.

This tool will neither start nor stop processes, or interact with running processes at all. That includes killing processes that are listening on a given PORT. It also won't list processes that are listening on a given port. The only thing it does is CRUD actions against a Procfile as is, and generate files from a Procfile.

If you need a tool that kills running processes, I suggest either looking for something else or writing your own.
